# Settings for ros_control control loop
hardware_control_loop:
   loop_hz: 125

# Settings for ros_control hardware interface
hardware_interface:
   sim_control_mode: 0 # 0: position, 1: velocity
   joints:
     - arm_1_joint
     - arm_2_joint
     - arm_3_joint
     - arm_4_joint
     - arm_5_joint
     - arm_6_joint

# Publish all joint states ----------------------------------
arm_joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 50

# Joint Trajectory Controller - position based -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
arm_pos_traj_controller:
   type: position_controllers/JointTrajectoryController
   publish_rate: 50
   joints:
     - arm_1_joint
     - arm_2_joint
     - arm_3_joint
     - arm_4_joint
     - arm_5_joint
     - arm_6_joint

# Joint Trajectory Controller - effort based -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
arm_eff_traj_controller:
    type: effort_controllers/JointTrajectoryController
    publish_rate: 50
    joints:
     - arm_1_joint
     - arm_2_joint
     - arm_3_joint
     - arm_4_joint
     - arm_5_joint
     - arm_6_joint
    gains:
        arm_1_joint: { p: 1000, d: 4, i: 0.01}
        arm_2_joint: { p: 5000, d: 6, i: 0.01}
        arm_3_joint: { p: 2000, d: 6, i: 0.01}
        arm_4_joint: { p: 2000, d: 6, i: 0.01}
        arm_5_joint: { p: 1000, d: 6, i: 0.01}
        arm_6_joint: { p: 100, d: 0, i: 0.01}

# Cartesian controller and cartesian handle -------------------------------
arm_cartesian_motion_controller:
    type: "position_controllers/CartesianMotionController"
    end_effector_link: "arm_tcp_link"
    robot_base_link: "arm_base_link"
    target_frame_topic: "/arm/target_pose"
    joints:
     - arm_1_joint
     - arm_2_joint
     - arm_3_joint
     - arm_4_joint
     - arm_5_joint
     - arm_6_joint
    solver:
        mass: 0.5
        inertia: 0.05
    pid_gains:
        trans_x: {p: 10.0, i: 0, d: 0}
        trans_y: {p: 10.0, i: 0, d: 0}
        trans_z: {p: 10.0, i: 0, d: 0}
        rot_x: {p: 1.0, i: 0, d: 0}
        rot_y: {p: 1.0, i: 0, d: 0}
        rot_z: {p: 1.0, i: 0, d: 0}

arm_motion_control_handle:
   type: "cartesian_controllers/MotionControlHandle"
   end_effector_link: "arm_tcp_link"
   robot_base_link: "arm_base_link"
   target_frame_topic: "/arm/target_pose"
   joints:
     - arm_1_joint
     - arm_2_joint
     - arm_3_joint
     - arm_4_joint
     - arm_5_joint
     - arm_6_joint
