gripper_left_effort_controller:
  type: effort_controllers/JointEffortController
  joint: gripper_left_joint_ur5e
  pid: {p: 3000.0, i: 1, d: 2, i_clamp_min: -1, i_clamp_max: 1}

gripper_right_effort_controller:
  type: effort_controllers/JointEffortController
  joint: gripper_right_joint_ur5e
  pid: {p: 1000.0, i: 1, d: 0, i_clamp_min: -1, i_clamp_max: 1}
